import { Component, OnInit } from '@angular/core';
import {FormControl, FormGroup, Validators} from '@angular/forms';
import {Organization, OrganizationService} from '../../services/organization.service';
import {Project, ProjectService, ProjectType} from '../../services/project.service';
import {AuthService} from '../../services/auth.service';
import {MatDialogRef} from '@angular/material/dialog';

@Component({
  selector: 'app-project-modal',
  templateUrl: './project-modal.component.html',
  styleUrls: ['./project-modal.component.scss']
})
export class ProjectModalComponent implements OnInit {

  organizations: Organization[] = [];

  projects: Project[] = [];
  projectForm: FormGroup;
  projectNameControl = new FormControl('', [Validators.required, Validators.pattern('^[a-zA-Z](?:-?[a-zA-Z0-9]+)*')]);
  projectKeyControl = new FormControl(
    '',
    [Validators.required,
      Validators.pattern('^[A-Z]*'),
      Validators.minLength(3),
      Validators.maxLength(5)]
  );
  organizationControl = new FormControl('', Validators.required);
  selectedOrganization: any;


  projectType: ProjectType;
  userProfile: any;

  constructor(private orgService: OrganizationService,
              private  dialog: MatDialogRef<ProjectModalComponent>,
              private ps: ProjectService,
              private auth: AuthService) {
    this.projectForm = new FormGroup({
      projectName: this.projectNameControl,
      projectKey: this.projectKeyControl,
      organizationControl: this.organizationControl
    });

    auth.userProfile$.subscribe(profile => this.userProfile = {...profile});
  }

  ngOnInit(): void {
    this.orgService
      .userOrganizations$
      .subscribe( (orgs) => {
        this.organizations = orgs;
        this.organizationControl.setValue(orgs[0].id);
      });

    this.ps.projects$.subscribe(projects => this.projects = projects);
  }

  create(): void{
    const project: Project = {
      name: this.projectNameControl.value,
      key: this.projectKeyControl.value,
      organizationId: this.organizationControl.value,
      type: this.projectType,
      leadId: this.userProfile.sub
    };

    this.ps.save(project).subscribe(proj => {
      console.log('project: ', proj);
      this.dialog.close();
    });
  }

  getProjectNameErrorMessage(): string {

    if (this.projectNameControl.hasError('required')) {
      return 'You must enter a value';
    }
    return (this.projectNameControl.hasError('pattern'))
      ? 'Project name should start with latin alphabet letters(case insensitive), can contain numbers and dash(inside)'
      : '';
  }
  getProjectKeyErrorMessage(): string {
    if (this.projectKeyControl.hasError('required')) {
      return 'You must enter a value';
    }
    else if (this.projectKeyControl.hasError('minLength')) {
      return 'Min length 3 characters';
    }
    else if (this.projectKeyControl.hasError('maxLength')) {
      return 'Max length 5 characters';

    }
    return (this.projectKeyControl.hasError('pattern'))
      ? 'Key name should contain only latin alphabet letters in upper case.'
      : '';
  }
  keyToUpperCase(): void {
    this.projectKeyControl.setValue(this.projectKeyControl.value.toUpperCase());
  }

  setAutoGeneratedKeyValue(pName: string): void {
    const chars = pName.replace(/[^a-zA-Z]+/g, '');
    if (chars.length > 2) {
      this.projectKeyControl.setValue(chars.toUpperCase().substring(0, 5));
    }
  }

  existsByOrganizationIdAndName(pName: string): void {
    const orgId = this.organizationControl.value;
    const projects1 = this.projects.filter(p => p.organizationId === orgId && p.name === pName);
    console.log('project length: ', projects1.length);
  }
  onKeyUpProjectNameControl(): void {
    const pName = this.projectNameControl.value.toString();
    this.setAutoGeneratedKeyValue(pName);
    this.existsByOrganizationIdAndName(pName);
  }
}
