import { Component, OnInit } from '@angular/core';
import {ModalDialogParams} from '@nativescript/angular';
import {OrganizationService} from '@src/app/services/organization.service';
import {ProjectService} from '@src/app/web/project/services/project.service';
import {Organization, Project} from '@src/app/shared/atlas/entity.service';

@Component({
  selector: 'app-project-modal',
  templateUrl: './project-modal.component.tns.html',
  styleUrls: ['./project-modal.component.tns.scss']
})
export class ProjectModalComponent implements OnInit {

  organizations: Organization[] = [];
  projects: Project[] = [];
  nameOrg: '';
  namePrj: '';
  selectedIndex: '';


  projectType = 1;
  constructor(
    private modalParams: ModalDialogParams,
    private organizationService: OrganizationService,
    private projectService: ProjectService
  ) { }

  ngOnInit(): void {


    this.organizationService.userOrganizations$.subscribe((orgs) => {
      this.organizations = orgs;
    });

    this.projectService.projects$.subscribe(projects => this.projects = projects);
  }


  create(): void{
    console.log(this.nameOrg);


  }

  setAutoGeneratedKeyValue(pName: string): void {
    const chars = pName.replace(/[^a-zA-Z0-9]+/g, '');
    if (chars.length > 2) {
      // this.projectKeyControl.setValue(chars.toUpperCase().substring(0, 5));
    }
  }

  onKeyUpProjectNameControl(): void {
    // const pName = this.projectNameControl.value.toString();
    // this.setAutoGeneratedKeyValue(pName);
  }
}
