import { Component, OnInit } from '@angular/core';
import {ModalDialogParams} from '@nativescript/angular';
import {OrganizationService} from '@src/app/services/organization.service';
import {ProjectService} from '@src/app/web/project/services/project.service';
import {Organization, Project} from '@src/app/shared/atlas/entity.service';
import {SelectedIndexChangedEventData} from 'nativescript-drop-down';

@Component({
  selector: 'app-project-modal',
  templateUrl: './project-modal.component.tns.html',
  styleUrls: ['./project-modal.component.tns.scss']
})
export class ProjectModalComponent implements OnInit {

  organizations: Organization[] = [];
  orgName: string[];
  orgFilter: Organization;
  projects: Project[] = [];
  nameOrg: '';
  namePrj: string;
  keyProject: string;
  selectedIndex: '';


  projectType = 1;
  constructor(
    private modalParams: ModalDialogParams,
    private organizationService: OrganizationService,
    private projectService: ProjectService
  ) { }

  ngOnInit(): void {
    this.organizationService.userOrganizations$.subscribe((orgs) => {
      this.organizations = orgs;
      this.orgName = Array.from(orgs, org => org.name);
    });
    this.projectService.projects$.subscribe(projects => this.projects = projects);
  }

  create(): void{


      console.log('try creare project', this.namePrj);

      if (this.namePrj) {
      const project: Project = {
        name: this.namePrj,
        key:  this.setAutoGeneratedKeyValue(this.namePrj),
        organizationId: this.orgFilter.id,
        type: this.projectType,
        leadId: '00u2v5jxvoGXWqQTw4x7'
      };
         console.log('project: ',project);
      this.projectService.create(project).subscribe(
        proj => {
          this.projects.push(proj);
          this.projectService.updateProjectsSubject(this.projects);
          this.modalParams.closeCallback();
        }, error => {

        }
      );
    }



  }

  setAutoGeneratedKeyValue(pName: string): string {
    const chars = pName.replace(/[^a-zA-Z0-9]+/g, '');
    if (chars.length > 2) {
       return  chars.toUpperCase().substring(0, 5);
    }
    return chars;
  }

  onKeyUpProjectNameControl(): void {
     const pName = this.namePrj.toString();
     this.setAutoGeneratedKeyValue(pName);
  }


  public onchange(args: SelectedIndexChangedEventData): void {
    this.orgFilter = this.organizations.find(org => org.name === this.orgName[args.newIndex]);

  }

  public onopen(): void {
    console.log("Drop Down opened.");
  }
  onclose() {

  }
}
